site_name: My Project Documentation
site_url: https://USERNAME.github.io/REPO
site_description: Official documentation for My Project
site_author: My Team

# Theme settings
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: images/favicon.png
  favicon: images/logo.png

# Navigation structure
nav:
  - Home: index.md
  - Tutorials:
    - Introduction: tutorials/intro.md
    - Advanced Topics: tutorials/advanced.md
  - Getting Started:
      - Development: getting-started/dev-setup.md
      - Installation: getting-started/installation.md
  - Documentation:
      - Architecture: documentation/architecture.md
      - App Design : documentation/AppDesigns.md
      - Features:
          - Feature 1: documentation/Features/feature1.md
          - Feature 2: documentation/Features/feature2.md
          - Feature 3: documentation/Features/feature3.md
          - Feature 4: documentation/Features/feature4.md
      - Uml Diagrams:
          - Sprint 1: documentation/uml/sprint1.md


  - Workflow:
      - Release Notes: workflow/release-notes.md
      - Git Methodology: workflow/git-methodology.md
      - Testing and Quality Assurance: workflow/testing.md
      - Sprint Checklist: workflow/sprint-checklists.md
      - Meetings: workflow/meetings.md


      
  - Reports:
      - Makomane Tau (2652227): reports/2652227.md
###########################################
# Plugins
plugins:
  - search
  - tags
  - awesome-pages
  - git-revision-date-localized:
      timezone: "Etc/UTC"
      fallback_to_build_date: true
  - minify:
      minify_html: true

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tilde

# Extra site config
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/USERNAME/REPO
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/YOUR_HANDLE
