name: Deploy MkDocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin mkdocs-tags-plugin pymdown-extensions
      - run: mkdocs gh-deploy --force
        env:
          # This token is automatically provided by GitHub Actions for the repo and
          # allows pushing to gh-pages branch.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
